name: Git Workshop Demo

on:
  push:
    branches:
      - 'feature/**'
      - 'bugfix/**'
      - 'chore/**'
env:
  SERVER_IP: '127.0.0.1'
  COMPANY_NAME: 'NTPLC'
  REPO_NAME: ${{ github.repository }}
jobs:
  job-1:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - run: echo "Hello ${{ env.COMPANY_NAME }}"
      - run: echo ${{ env.SERVER_IP }}
      - run: echo "Repo Name ${{ env.REPO_NAME }}"
      - run: echo "APP NAME ${{ vars.APP_NAME }}"
      - run: echo "APP KEY ${{ secrets.APP_KEY }}"
  job-2:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - run: echo "Action ${{ github.action }}"
      - run: echo "Repo URL ${{ github.repository }}"
      - run: echo "Server ${{ vars.SERVER_IP }}"